
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// DEPARTAMENTO
export const CREATE_DEPARTAMENTO_SUCCESS = "CREATE_DEPARTAMENTO_SUCCESS";
export const DELETE_DEPARTAMENTO_SUCCESS = "DELETE_DEPARTAMENTO_SUCCESS";
export const GET_DEPARTAMENTO_SUCCESS = "GET_DEPARTAMENTO_SUCCESS";
export const LIST_DEPARTAMENTO_SUCCESS = "LIST_DEPARTAMENTO_SUCCESS";
export const UPDATE_DEPARTAMENTO_SUCCESS = "UPDATE_DEPARTAMENTO_SUCCESS";

// MUNICIPIO
export const CREATE_MUNICIPIO_SUCCESS = "CREATE_MUNICIPIO_SUCCESS";
export const DELETE_MUNICIPIO_SUCCESS = "DELETE_MUNICIPIO_SUCCESS";
export const FINDBYDEPARTAMENTO_MUNICIPIO_SUCCESS = "FINDBYDEPARTAMENTO_MUNICIPIO_SUCCESS";
export const GET_MUNICIPIO_SUCCESS = "GET_MUNICIPIO_SUCCESS";
export const LIST_MUNICIPIO_SUCCESS = "LIST_MUNICIPIO_SUCCESS";
export const UPDATE_MUNICIPIO_SUCCESS = "UPDATE_MUNICIPIO_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
